ROOT = ../../..

all:
	mkdir -p bin
	cd src ; gcc -Wall -g -I $(ROOT)/examples/AN01034_using_the_device_control_library_over_usb/host/libusb/OSX64 -o ../bin/usb_end_to_end_hardware_host.bin -I $(ROOT)/lib_device_control/api -I $(ROOT)/lib_device_control/src -I $(ROOT)/lib_device_control/host -I $(ROOT)/lib_device_control/host $(ROOT)/examples/AN01034_using_the_device_control_library_over_usb/host/libusb/OSX64/libusb-1.0.0.dylib -D USE_USB $(ROOT)/lib_device_control/host/device_access_usb.c $(ROOT)/lib_device_control/host/util.c host.c signals.c

clean:
	rm -rf bin
